filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'

checks:
    php:
        code_rating: true
        duplication: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        param_doc_comment_if_not_inferrable: true
        no_goto: true
        newline_at_end_of_file: true
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_line_ending: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: "PSR2"
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'

    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
