<?php

use DI\ContainerBuilder;
use FeedFaker\Classes\OfficeFaker;
use FeedFaker\Models\Office;

class BaseModelTest extends PHPUnit_Framework_TestCase
{
    public $container;
    /** @var Office $office */
    public $office;

    public function setUp()
    {
        // need to have your Config/Settings file populated or these tests will fail
        $containerBuilder = new ContainerBuilder;
        $containerBuilder->addDefinitions(__DIR__ . '/settings_fixture.php');
        $this->container = $containerBuilder->build();

        $office_faker = new OfficeFaker($this->container);
        $this->office = $office_faker->generate();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testToArray()
    {
        $office_array = $this->office->toArray();

        $this->assertTrue(is_array($office_array));
        $this->assertArrayHasKey('OfficeKey', $office_array);
        $this->assertArrayHasKey('OfficeFax', $office_array);
        $this->assertArrayHasKey('OfficePostalCode', $office_array);
    }

    public function testFromArray()
    {
        $office_array = $this->office->toArray();

        $office = new Office();
        $office->fromArray($office_array);

        $this->assertSame($office_array['OfficeKey'], $office->getOfficeKey());
        $this->assertSame($office_array['OfficeFax'], $office->getOfficeFax());
        $this->assertSame($office_array['OfficePostalCode'], $office->getOfficePostalCode());
    }

}
