<?php

namespace FeedFaker\Providers;

use Faker\Factory;
use Faker\Generator;
use Faker\Provider\Base;

class FeatureProvider extends Base
{
    public $faker;

    public function __construct(Generator $generator)
    {
        $this->faker = Factory::create();
        parent::__construct($generator);
    }

    public function getFeatureList($field_name, $count = 0)
    {
        $count_provided = true;
        $single_values = $this->getSingleValues();
        if (!$count) {
            if (in_array($field_name, $single_values)) {
                $count_provided = true;
                $count = 1;
            } else {
                $count_provided = false;
                $count = $this->faker->numberBetween(1, 4);
            }
        }

        $return = [];
        $data_array = $this->getDataValues($field_name);

        // looking for a non-existent field-- get fake words
        if (empty($data_array)) {
            return $this->faker->words($count);
        } else if (count($data_array) <= $count) {
            return $data_array;
        }

        while (count(array_unique($return)) < $count) {
            $rand = array_rand($data_array);
            $return[] = $data_array[$rand];
        }

        // if we specifically asked for one value, don't return an array
        if ($count === 1 and $count_provided) {
            return $return[0];
        }

        return array_unique($return);
    }

    public function getAllEnums($field_name)
    {
        return $this->getDataValues($field_name);
    }

    public function getData()
    {
        return [
            'AccessibilityFeatures' => [
                '2+ Access Exits',
                '32 Inch Doors',
                '48 Inch Halls',
                'Chairlift',
                'Kitchen Modifications',
                'Handicap Access',
                'Flashing Doorbell',
                'Flooring Modifications',
                'Parking',
                'Wheelchair Access',
                'Wheelchair Adaptable',
                'Sight Modifications',
                'Roll In Shower',
                'Ramp- Main Level',
                'Doors Swing In',
                'Doors with Lever Handled',
                'Disability Access',
                'Wheelchair Ramps',
                'Other',
                ],
            'Appliances' => [
                'Dishwasher',
                'Refrigerator',
                'Stove/Range',
                'Central Vacuum',
                'Garbage Disposal',
                'Trash Compactor',
                'Ice Maker',
                'Portable Dishwasher',
                'Water Filter',
                'Water Purifier',
                'Water Conditioner',
                'Washer',
                'Dryer',
                'Microwave',
                'Convection Oven',
                'Oven',
                'Range',
                'Range Hood',
                'Oven-Gas',
                'Gas Grill',
                'Double Oven',
                'Warmer Drawer',
                ],
            'AssociationAmenities' => [
                'Banquet Center',
                'Barbeque',
                'Biking Trails',
                'Billiard Room',
                'Bocce Court',
                'Card Room',
                'Club House',
                'Common RV Parking',
                'Controlled Access',
                'Dock',
                'Fire Pit',
                'Fitness Center',
                'Gated Community',
                'Gated Parking',
                'Golf',
                'Guard',
                'Guest Parking',
                'Gym',
                'Horse Trails',
                'Hot Water',
                'Meeting Room',
                'Onsite Property Management',
                'Other Courts',
                'Paddle Tennis',
                'Sauna',
                'Security',
                'Sport Court',
                'Steam Room',
                'Storage',
                'Tennis Courts',
                'Picnic Area',
                'Lake or Pond',
                'Other',
                ],
            'AssociationFeeIncludes' => [
                'Cable TV',
                'Electricity',
                'Gas',
                'Security',
                'Sewer',
                'Trash',
                'Water',
                'Building and Grounds',
                'Clubhouse',
                'Insurance',
                'Maintenance',
                'Alarm System',
                'Concierge',
                'Utilities',
                ],
            'Basement' => [
                'Crawl',
                'Full',
                'Partial',
                ],
            'BuildingFeatures' => [
                'Cable TV',
                'High Speed Internet',
                'Master Walk in Closet',
                'Sauna',
                'Security System',
                'Sump Pump',
                'Whirlpool Tub',
                'Satellite Dish',
                'Hot Tub',
                'Heated Garage',
                ],
            'CommunityFeatures' => [
                'Playground',
                'Pool',
                'Dog Park',
                'Clubhouse',
                'Fitness Center',
                'Tanning Room',
                'Media Room',
                'Meeting Room',
                'Gated Entrance',
                'Boat Ramp',
                'Dock',
                'RV Access / Parking',
                'Golf Course',
                ],
            'ConstructionMaterials' => [
                'Brick',
                'Combination',
                'Frame',
                'Hardee Plank',
                'Log',
                'Masonite',
                'Vinyl',
                'Stucco',
                'Wood',
                'Aluminum',
                'Asphalt',
                'Block',
                'Concrete',
                'Glass',
                'Steel',
                'Adobe',
                'Cement Board',
                'Clapboard',
                'Flagstone',
                'Plaster',
                'Redwood',
                'Stone Veneer',
                'Stone and Wood',
                'Brick and Wood',
                ],
            'Cooling' => [
                'Central Air',
                'Geo Thermal',
                'Wall',
                'Window',
                ],
            'DoorFeatures' => [
                'Double Entry Door',
                'French Doors',
                'Insulated Doors',
                'Sliding Glass Doors',
                ],
            'ExteriorFeatures' => [
                'Children\'s Playset',
                'Clothes Line',
                'Deck',
                'Dog run',
                'Fire pit',
                'Garage Door Opener',
                'Garden',
                'Patio',
                'Pool In Ground',
                'Pool Above Ground',
                'Porch',
                'Privacy Fence',
                'Sprinkler system',
                ],
            'Fencing' => [
                'Wood',
                'Barbed Wire',
                'Electric Fence',
                'Block Wall',
                'Brick Wall',
                'Cedar Fence',
                'Chain Link',
                'Cross Fence',
                'Glass / Plexiglass',
                'Grapestock',
                'Livestock Fence',
                'Masonry Fence',
                'Privacy Fence',
                'Redwood',
                'Split Rail',
                'Vinyl Fence',
                'Wire Fence',
                'Wrought Iron',
                'Stucco Wall',
                ],
            'FireplaceFeatures' => [
                'Blower Fan',
                'Free Standing',
                'Heatilator',
                'Circular',
                'Decorative',
                'Fire Pit',
                'Raised Hearth',
                'See Through',
                'Two Way',
                'Wood Stove Insert',
                ],
            'FoundationDetails' => [
                'Concrete Block',
                'Concrete Slab',
                'Permanent',
                'Combination',
                'Concrete Perimeter',
                'Pier and Beam',
                'Pillar / Post',
                'Other',
                'Pier Jacks',
                'Quake Bracing',
                'Tie Down',
                ],
            'Flooring' => [
                'Hardwood',
                'Laminate',
                'Bamboo',
                'Tile',
                'Brick',
                'Carpet',
                'Vinyl / Linoleum',
            ],
            'Gas' => [
                'Propane',
                'Natural Gas',
                'Propane Tank',
                ],
            'GreenEnergyGeneration' => [
                'Geothermal',
                'Solar',
                'Wind',
                ],
            'GreenSustainability' => [
                'Biodegradable',
                'Conserving',
                'Recyclable',
                'Recycled',
                'Renewable',
                ],
            'Heating' => [
                'Electric Baseboard',
                'Steam',
                'Electric Hot Water',
                'Oil',
                'Coal',
                'Electric Forced Air',
                'Electric',
                'Gas',
                'Gravity',
                'Gas Hot Water',
                'Solar',
                'Gas Forced Air',
                'Gas Space Heater',
                'Inside Wood',
                'Oil Forced Air',
                'Oil Space Heater',
                'Oil Hot Water',
                'Convection',
                'Pellet Stove',
                'Geo Thermal',
                'Outside Wood',
                'In Floor Radiant',
                ],
            'InteriorFeatures' => [
                'High Ceilings',
                'Bar',
                'Elevator',
                'Intercom',
                'Vaulted Ceilings',
                'Wet Bar',
                'Paneled Walls',
                'Built-Ins',
                'Furnished',
                'Electronic Air Cleaner',
                'Dumbwaiter',
                'Home Automation',
                'Chair Rails',
                'Crown Molding',
                'Laundry Chute',
                'Living Room Balcony',
                'Open Floor Plan',
                'Recessed Lighting',
                'Sump Pump',
                'Wainscotting',
                '220V Throughout',
                'Wired for Surround',
                'Wired for High Speed Data',
                'Phone System',
                'Storage Space',
                'Gas Dryer Hookup',
                ],
            'LaundryFeatures' => [
                'In Kitchen',
                'In Garage',
                'Folding Table',
                'Utility Sink',
                'Laundry Chute',
                'Hanging Racks',
                'Cabinets',
                'Ironing Board',
                ],
            'LockboxLocation' => [
                'Front door',
                'Back door',
                'Railing',
                'Gas meter',
                'Garage',
                'Back gate',
                'Porch',
                'Light fixture',
            ],
            'LotFeatures' => [
                'Lot Shape- Irregular',
                'Lot Shape- Flag',
                'Lot Level',
                'Curbs',
                'Fenced',
                'Horse Property',
                'Landscaped',
                'Raw Land',
                'Street Lighting',
                'Alley Paved',
                'Back Yard',
                'Corners Established',
                'Front Yard',
                'Fully Fenced',
                'Lawn',
                'Street Paved',
                'Room for Pool',
                'Seawall',
                'Secluded',
                'Percolate',
                'Wooded',
                'Gated Community',
                'Gutters',
                'Automatic Gate',
                'Utilities Overhead',
                'Utilities Underground',
                'Ranch',
                'Agricultural',
                'Storm Drains',
                'Sidewalks',
                ],
            'OtherParking' => [
                'Street Parking',
                'Alley Parking',
                'Carport',
                'Shared Garage',
                ],
            'ParkingFeatures' => [
                'Gated',
                'Permit / Decal',
                'Circular Driveway',
                'Converted Garage',
                'Direct Garage Access',
                'Garage Door Opener',
                'Auto Driveway Gate',
                'RV Covered',
                'RV Gated',
                'Workshop',
                'Uncovered',
                'Private Garage',
                'Shared Driveway',
                'Air Conditioned Garage',
                'Controlled Entrance',
                'Driveway',
                'Driveway - Brick',
                'Driveway - Pavers',
                'Driveway - Gravel',
                ],
            'PatioAndPorchFeatures' => [
                'Rooftop Deck',
                'Porch',
                'Arizona Room',
                'Awning',
                'Brick',
                'Concrete Slab',
                'Covered',
                'Enclosed',
                'Enclosed Glass',
                'Patio Open',
                'Wood',
                'Tile',
                'Slab',
                'Wrap Around',
                'Screened',
                'Porch - Front',
                'Porch - Rear',
                'Lap Pool',
                ],
            'PoolFeatures' => [
                'Exercise Pool',
                'Heated',
                'Black Bottom',
                'Association Pool',
                'Community Pool',
                'Filtered',
                'Fenced',
                'Infinity Pool',
                'Private Pool',
                'Solar Heated Pool',
                ],
            'Roof' => [
                'Asphalt Comp',
                'Cedar Shake',
                'Metal',
                'Hot Tar',
                'Slate / Tile',
                ],
            'SecurityFeatures' => [
                'Card / Code Access',
                '24 Hour',
                'Fire / Smoke Alarms',
                'Resident Manager',
                'Automatic Gate',
                'Fire Sprinklers',
                'Closed Circuit TV',
                'Exterior Security Lights',
                'Guarded',
                'Prewired for Alarm',
                'Window Bars',
                'Other',
                'Security System',
                ],
            'Sewer' => [
                'Cesspool',
                'Other',
                'Public Hookup Available',
                'Sewer',
                'Sewer Bond',
                'Assessment',
                'Connected on Bond',
                'In Street',
                'In Street Paid',
                'On Site',
                'Septic Tank',
                'Unknown',
                ],
            'SpaFeatures' => [
                'Association Spa',
                'Bath Tub',
                'Community',
                'Fenced',
                'Heated',
                'Hot Tub',
                'Indoor',
                'Other',
                'Private Portable',
                'Private Spa',
                'Solar Heated Spa',
                ],
            'ArchitecturalStyle' => [
                '1 Story',
                '1 Story W/O',
                '1.5 Story',
                '1.75 Story',
                '2 1/4 Story',
                '2 Story',
                '2.5 Story',
                '3 Story',
                'A-Frame',
                'Bi-Level',
                'Bungalow',
                'Cabin',
                'Cape Cod',
                'Chalet',
                'Condo',
                'Contemporary',
                'Cottage',
                'Duplex',
                'Log',
                'Manufactured',
                'Mobile',
                'Multi-Level',
                'Quad-Level',
                'Raised Bungalow',
                'Raised Ranch',
                'Ranch',
                'Split Level',
                'Tri-Level',
                'Victorian',
                'Walk Out Ranch',
            ],
            'Utilities' => [
                'Cable Available',
                'See Remarks',
                'Underground Utilities',
                'Propane',
                'Phone Available',
                'Phone Not Available',
                'Phone Connected',
                'Water Connected',
                'Natural Gas Available',
                'Sewer Connected',
                'Sewer Available',
                'Water Available',
                ],
            'Vegetation' => [
                'Fruit Trees',
                'Sod Grass',
                'Perennial Flowers',
                'Hedges',
                'Planter boxes',
                ],
            'WaterfrontFeatures' => [
                'Dock',
                'Sandy Beach',
                'Gravel Beach',
                'Private Access',
                'Shared Access',
                'Boat Slip',
                'Boat Ramp',
                'Swim Platform',
                'Picnic Area',
                'Shared Dock',
                'Private Dock',
                ],
            'WaterSource' => [
                'Public',
                'Well',
                'Spring',
                'Artesian',
                'Shared Well',
                ],
            'WindowFeatures' => [
                'Bay Window(s)',
                'Impact Resistant',
                'Awnings',
                'Drapes / Curtains',
                'Garden Window',
                'Screens',
                'Plantation Shutters',
                'Skylights',
                'Stained Glass',
                'Vertical Blinds',
                'Window Blinds',
                'Window Shutters',
                'Mini Blinds'
                ],
            'GreenBuildingVerificationType' => [
                'ENERGY STAR Certified Homes',
                'Home Energy Score',
                'Home Energy Upgrade Certificate of Energy Efficiency Improvements',
                'Home Energy Upgrade Certificate of Energy Efficiency Performance',
                'Living Building Challenge',
                'Certified Passive House',
                'HERS Index Score',
                'WaterSense',
                'LEED For Homes',
                'NGBS Whole-Home Remodel',
                'PHIUS+',
                'Home Performance with ENERGY STAR',
                'NGBS New Construction',
                'NGBS Small Projects Remodel',
                'Zero Energy Ready Home',
                'Indoor airPLUS',
                'EnerPHit'
            ],
            'OwnershipType' => [
                'Corporation',
                'LLC',
                'Partnership',
                'Sole Proprietor'
            ],
            'PropertySubType' => [
                'Apartment',
                'Boat Slip',
                'Single Family Residence',
                'Deeded Parking',
                'Cabin',
                'Condominium',
                'Duplex',
                'Farm',
                'Ranch',
                'Manufactured Home',
                'Mobile Home',
                'Own Your Own',
                'Quadruplex',
                'Stock Cooperative',
                'Townhouse',
                'Timeshare',
                'Triplex',
                'Manufactured On Land'
            ],
            'RoomType' => [
                'Dining Room',
                'Living Room',
                'Family Room',
                'Basement',
                'Kitchen',
                'Master Bedroom',
                'Bedroom 1',
                'Bedroom 2',
                'Bedroom 3',
                'Bedroom 4',
                'Bedroom 5',
                'Master Bathroom',
                'Bathroom 1',
                'Bathroom 2',
                'Bathroom 3',
                'Bathroom 4',
                'Bathroom 5',
                'Den',
                'Office',
                'Great Room',
                'Utility Room',
                'Workshop',
                'Laundry',
                'Loft',
                'Bonus Room',
                'Game Room',
                'Media Room',
                'Library',
                'Exercise Room',
                'Gym',
                'Sauna'
            ],
            'Levels' => [
                'One',
                'Two',
                'Three Or More',
                'Multi\/Split'
            ],
            'BusinessType' => [
                'Accounting',
                'Administrative and Support',
                'Advertising',
                'Agriculture',
                'Animal Grooming',
                'Appliances',
                'Aquarium Supplies',
                'Arts and Entertainment',
                'Athletic',
                'Auto Body',
                'Auto Glass',
                'Auto Parts',
                'Auto Rent\/Lease',
                'Auto Repair-Specialty',
                'Auto Dealer',
                'Auto Stereo\/Alarm',
                'Auto Tires',
                'Auto Wrecking',
                'Auto Service',
                'Bakery',
                'Bar\/Tavern\/Lounge',
                'Barber\/Beauty',
                'Bed & Breakfast',
                'Books\/Cards\/Stationary',
                'Butcher',
                'Cabinets',
                'Candy\/Cookie',
                'Car Wash',
                'Carpet\/Tile',
                'Child Care',
                'Church',
                'Clothing',
                'Commercial',
                'Computer',
                'Construction\/Contractor',
                'Convalescent',
                'Convenience Store',
                'Dance Studio',
                'Decorator',
                'Dental',
                'Deli\/Catering',
                'Distribution',
                'Doughnut',
                'Drugstore',
                'Dry Cleaner',
                'Education\/School',
                'Electronics',
                'Employment',
                'Farm',
                'Fast Food',
                'Financial',
                'Fitness',
                'Florist\/Nursery',
                'Food & Beverage',
                'Forest Reserve',
                'Franchise',
                'Furniture',
                'Gas Station',
                'Gift Shop',
                'Grocery',
                'Hardware',
                'Health Food',
                'Health Services',
                'Hobby',
                'Home Cleaner',
                'Hospitality',
                'Hotel\/Motel',
                'Ice Cream\/Frozen Yogurt',
                'Industrial',
                'Jewelry',
                'Landscaping',
                'Laundromat',
                'Liquor Store',
                'Locksmith',
                'Manufacturing',
                'Medical',
                'Mixed',
                'Mobile\/Trailer Park',
                'Music',
                'Nursing Home',
                'Other',
                'Office Supply',
                'Paints',
                'Parking',
                'Pet Store',
                'Photographer',
                'Pizza',
                'Printing',
                'Professional Service',
                'Professional\/Office',
                'Real Estate',
                'Recreation',
                'Rental',
                'Residential',
                'Restaurant',
                'Retail',
                'Saddlery\/Harness',
                'Sporting Goods',
                'Storage',
                'Toys',
                'Transportation',
                'Travel',
                'Upholstery',
                'Utility',
                'Variety',
                'Video',
                'Wallpaper',
                'Warehouse',
                'Wholesale'
            ],
            'LeaseTerm' => [
                '12 Months',
                '24 Months',
                '6 Months',
                'Month To Month',
                'Negotiable',
                'Weekly',
                'None',
                'Other',
                'Renewal Option',
                'Short Term Lease'
            ],
            'ListingAgreement' => [
                'Exclusive Right To Lease',
                'Exclusive Agency',
                'Exclusive Right With Exception',
                'Exclusive Right To Sell',
                'Net',
                'Open',
                'Probate'
            ],
            'ListingService' => [
                'Full Service',
                'Limited Service',
                'Entry Only'
            ],
            'LotSizeUnits' => [
                'Acres',
                'Square Feet',
                'Square Meters'
            ],
            'PropertyType' => [
                'Residential',
                'Residential Lease',
                'Residential Income',
                'Manufactured In Park',
                'Land',
                'Commercial Sale',
                'Commercial Lease',
                'Business Opportunity',
                'Farm'
            ],
            'StateOrProvince' => [
                'AK',
                'AL',
                'AR',
                'AZ',
                'CA',
                'CO',
                'CT',
                'DC',
                'DE',
                'FL',
                'GA',
                'HI',
                'IA',
                'ID',
                'IL',
                'IN',
                'KS',
                'KY',
                'LA',
                'MA',
                'MD',
                'ME',
                'MI',
                'MN',
                'MO',
                'MS',
                'MT',
                'NC',
                'ND',
                'NE',
                'NH',
                'NJ',
                'NM',
                'NV',
                'NY',
                'OH',
                'OK',
                'OR',
                'PA',
                'RI',
                'SC',
                'SD',
                'TN',
                'TX',
                'UT',
                'VA',
                'VI',
                'VT',
                'WA',
                'WI',
                'WV',
                'WY',
                'AB',
                'BC',
                'MB',
                'NB',
                'NF',
                'NS',
                'NT',
                'NU',
                'ON',
                'PE',
                'QC',
                'SK',
                'YT'
            ],
            'MemberStatus' => [
                'Active',
                'Inactive'
            ],
            'OfficeStatus' => [
                'Active',
                'Inactive'
            ],
            'ResourceName' => [
                'Property',
                'Member',
                'Office',
                'Contacts'
            ],
            'OpenHouseType' => [
                'Public',
                'Broker',
                'Office'
            ],
            'AssociationFeeFrequency' => [
                'Monthly',
                'Quarterly',
                'Yearly'
            ],
            'AssociationFeeIncludes' => [
                'Cable TV',
                'Earthquake Insurance',
                'Electricity',
                'Gas',
                'Insurance',
                'Maintenance Exterior',
                'Maintenance Grounds',
                'Pest Control',
                'Security',
                'Sewer',
                'Snow Removal',
                'Trash',
                'Utilities',
                'Water'
            ],
            'Attended' => [
                'Agent',
                'Seller',
                'Unattended'
            ],
            'BuyerFinancing' => [
                'Assumed',
                'Cash',
                'Contract',
                'Conventional',
                'FHA',
                'FHA 203(b)',
                'FHA 203(k)',
                'Other',
                'Private',
                'Seller Financing',
                'Trust Deed',
                'USDA',
                'VA'
            ],
            'ClassName' => [
                'Business Opportunity',
                'Commercial Lease',
                'Commercial Sale',
                'Contacts',
                'Cross Property',
                'Farm',
                'History Transactional',
                'Land',
                'Manufactured In Park',
                'Media',
                'Member',
                'Office',
                'Open House',
                'Residential',
                'Residential Income',
                'Residential Lease',
                'Saved Search'
            ],
            'CommonWalls' => [
                '1 Common Wall',
                '2+ Common Walls',
                'End Unit',
                'No Common Walls',
                'No One Above',
                'No One Below'
            ],
            'CurrentFinancing' => [
                'Assumable',
                'Contract',
                'Conventional',
                'FHA',
                'FHA 203(b)',
                'FHA 203(k)',
                'None',
                'Other',
                'Leased Renewables',
                'Power Purchase Agreement',
                'Private',
                'Property-Assessed Clean Energy',
                'Trust Deed',
                'USDA',
                'VA'
            ],
            'ExistingLeaseType' => [
                'Absolute Net',
                'CPI Adjustment',
                'Escalation Clause',
                'Gross',
                'Ground Lease',
                'Net',
                'NN',
                'NNN',
                'Oral'
            ],
            'FinancialDataSource' => [
                'Accountant',
                'Owner',
                'Property Manager'
            ],
            'IncomeIncludes' => [
                'Laundry',
                'Parking',
                'Recreation',
                'Rent Only',
                'RV Storage',
                'Storage'
            ],
            'LeaseAmountFrequency' => [
                'Month',
                'Week',
                'Year'
            ],
            'LeaseRenewalCompensation' => [
                'Call Listing Agent',
                'Call Listing Office',
                'Commission Paid On Tenant Purchase',
                'No Renewal Commission',
                'Renewal Commission Paid'
            ],
            'ListingTerms' => [
                '1031 Exchange',
                'All Inclusive Trust Deed',
                'Assumable',
                'Cash',
                'Contract',
                'Conventional',
                'Existing Bonds',
                'FHA',
                'Land Use Fee',
                'Lease Back',
                'Lease Option',
                'Lease Purchase',
                'Lien Release',
                'Owner May Carry',
                'Owner Pay Points',
                'Owner Will Carry',
                'Private Financing Available',
                'Relocation Property',
                'Seller Equity Share',
                'Special Funding',
                'Submit',
                'Trade',
                'Trust Conveyance',
                'Trust Deed',
                'USDA Loan',
                'VA Loan'
            ],
            'MediaCategory' => [
                'Photo',
                'Video',
                'Branded Virtual Tour',
                'Unbranded Virtual Tour',
                'Document',
                'Floor Plan',
                'Office Logo',
                'Office Photo',
                'Agent Photo'
            ],
            'MediaType' => [
                'gif',
                'jpeg',
                'png',
                'tiff',
                'mpeg',
                'mp4',
                'quicktime',
                'wmv',
                'pdf',
                'rtf',
                'txt',
                'doc',
                'docx',
                'xls',
                'xlsx'
            ],
            'MemberType' => [
                'Association Staff',
                'Designated REALTOR Appraiser',
                'Designated REALTOR Participant',
                'MLS Only Appraiser',
                'MLS Only Broker',
                'MLS Only Salesperson',
                'MLS Staff',
                'Non Member\/Vendor',
                'Office Manager',
                'REALTOR Appraiser',
                'REALTOR Salesperson',
                'Unlicensed Assistant'
            ],
            'OccupantType' => [
                'Owner',
                'Tenant',
                'Vacant'
            ],
            'OfficeType' => [
                'Affiliate',
                'Appraiser',
                'Association',
                'MLS',
                'MLS Only Branch',
                'MLS Only Firm',
                'MLS Only Office',
                'Non Member\/Vendor',
                'Realtor Branch Office',
                'Realtor Firm',
                'Realtor Office'
            ],
            'OperatingExpenseIncludes' => [
                'Accounting',
                'Advertising',
                'Association',
                'Cable TV',
                'Capital Improvements',
                'Depreciation',
                'Equipment Rental',
                'Fuel',
                'Furniture Replacement',
                'Gardener',
                'Insurance',
                'Legal',
                'Licenses',
                'Maintenance',
                'Maintenance Grounds',
                'Maintenance Structure',
                'Manager',
                'Mortgage\/Loans',
                'New Tax',
                'Other',
                'Parking',
                'Pest Control',
                'Pool\/Spa',
                'Professional Management',
                'Security',
                'Snow Removal',
                'Staff',
                'Supplies',
                'Trash',
                'Utilities',
                'Vacancy Allowance',
                'Water\/Sewer',
                'Workmans Compensation'
            ],
            'Possession' => [
                'Close Of Escrow',
                'Close Plus 1 Day',
                'Close Plus 2 Days',
                'Close Plus 3 Days',
                'Close Plus 3 to 5 Days',
                'Close Plus 30 Days',
                'Negotiable',
                'Rental Agreement',
                'See Remarks',
                'Seller Rent Back',
                'Subject To Tenant Rights'
            ],
            'ShowingContactType' => [
                'Agent',
                'Occupant',
                'Owner',
                'Property Manager'
            ],
            'SpecialLicenses' => [
                'Beer\/Wine',
                'Class H',
                'Entertainment',
                'Franchise',
                'Gambling',
                'Liquor',
                'Liquor 5 Years Or Less',
                'Liquor 5 Years Or More',
                'Liquor-Off Sale',
                'Liquor-On Sale',
                'None',
                'Other',
                'Professional'
            ],
            'SpecialListingConditions' => [
                'Auction',
                'HUD Owned',
                'In Foreclosure',
                'Notice Of Default',
                'Probate Listing',
                'Real Estate Owned',
                'Short Sale',
                'Standard',
                'Third Party Approval',
                'Bankruptcy Property'
            ],
            'PetsAllowed' => [
                'Yes',
                'No',
                'Call',
                'Cats OK',
                'Dogs OK',
                'Number Limit',
                'Size Limit',
                'Breed Restrictions'
            ],
            'HoursDaysofOperation' => [
                'Open 24 Hours',
                'Open 8 Hours\/Day',
                'Open -8 Hours\/Day',
                'Open 8+ Hours\/Day',
                'Open 7 Days',
                'Open Monday-Friday',
                'Open Sunday',
                'Open Saturday',
                'Evenings Only'
            ],
            'ContactType' => [
                'Lead'
            ],
            'CompensationType' => [
                '$',
                '%',
                'See Remarks'
            ],
            'AreaUnits' => [
                'Square Feet',
                'Square Meters'
            ],
            'TeamStatus' => [
                'Active',
                'Inactive'
            ],
            'OpenHouseStatus' => [
                'Active',
                'Canceled',
                'Ended'
            ],
            'AreaSource' => [
                'Appraiser',
                'Assessor',
                'Builder',
                'Estimated',
                'Other',
                'Owner',
                'Plans',
                'Public Records',
                'See Remarks'
            ],
            'BodyType' => [
                'Double Wide',
                'Expando',
                'Quad Wide',
                'See Remarks',
                'Single Wide',
                'Triple Wide'
            ],
            'ChangeType' => [
                'Active',
                'Active Under Contract',
                'Back On Market',
                'Canceled',
                'Closed',
                'Deleted',
                'Expired',
                'Hold',
                'New Listing',
                'Pending',
                'Price Change',
                'Withdrawn'
            ],
            'Concessions' => [
                'Call Listing Agent',
                'No',
                'Yes'
            ],
            'ConstructionMaterials' => [
                'Adobe',
                'Aluminum Siding',
                'Asbestos',
                'Asphalt',
                'Attic\/Crawl Hatchway(s) Insulated',
                'Batts Insulation',
                'Block',
                'Blown-In Insulation',
                'Board & Batten Siding',
                'Brick',
                'Brick Veneer',
                'Cedar',
                'Cement Siding',
                'Clapboard',
                'Concrete',
                'Ducts Professionally Air-Sealed',
                'Exterior Duct-Work is Insulated',
                'Foam Insulation',
                'Fiber Cement',
                'Fiberglass Siding',
                'Frame',
                'Glass',
                'HardiPlank Type',
                'ICFs (Insulated Concrete Forms)',
                'ICAT Recessed Lighting',
                'Lap Siding',
                'Log',
                'Log Siding',
                'Low VOC Insulation',
                'Masonite',
                'Metal Siding',
                'Natural Building',
                'Other',
                'Plaster',
                'Radiant Barrier',
                'Rammed Earth',
                'Recycled\/Bio-Based Insulation',
                'Redwood Siding',
                'See Remarks',
                'Shake Siding',
                'Shingle Siding',
                'Slump Block',
                'Spray Foam Insulation',
                'Steel Siding',
                'Stone',
                'Stone Veneer',
                'Straw',
                'Stucco',
                'Synthetic Stucco',
                'Unknown',
                'Vertical Siding',
                'Vinyl Siding',
                'Wood Siding'
            ],
            'Country' => [
                'AF',
                'AL',
                'DZ',
                'AS',
                'AD',
                'AO',
                'AI',
                'AQ',
                'AG',
                'AR',
                'AM',
                'AW',
                'AU',
                'AT',
                'AZ',
                'BS',
                'BH',
                'BD',
                'BB',
                'BY',
                'BE',
                'BZ',
                'BJ',
                'BM',
                'BT',
                'BO',
                'BA',
                'BW',
                'BV',
                'BR',
                'IO',
                'BN',
                'BG',
                'BF',
                'BI',
                'KH',
                'CM',
                'CA',
                'CV',
                'KY',
                'CF',
                'TD',
                'CL',
                'CN',
                'CX',
                'CC',
                'CO',
                'KM',
                'CG',
                'CD',
                'CK',
                'CR',
                'CI',
                'HR',
                'CU',
                'CY',
                'CZ',
                'DK',
                'DJ',
                'DM',
                'DO',
                'EC',
                'EG',
                'SV',
                'GQ',
                'ER',
                'EE',
                'ET',
                'FK',
                'FO',
                'FJ',
                'FI',
                'FR',
                'GF',
                'PF',
                'TF',
                'GA',
                'GM',
                'GE',
                'DE',
                'GH',
                'GI',
                'GR',
                'GL',
                'GD',
                'GP',
                'GU',
                'GT',
                'GG',
                'GN',
                'GW',
                'GY',
                'HT',
                'HM',
                'VA',
                'HN',
                'HK',
                'HU',
                'IS',
                'IN',
                'ID',
                'IR',
                'IQ',
                'IE',
                'IM',
                'IL',
                'IT',
                'JM',
                'JP',
                'JE',
                'JO',
                'KZ',
                'KE',
                'KI',
                'KP',
                'KR',
                'KW',
                'KG',
                'AX',
                'LA',
                'LV',
                'LB',
                'LS',
                'LR',
                'LY',
                'LI',
                'LT',
                'LU',
                'MO',
                'MK',
                'MG',
                'MW',
                'MY',
                'MV',
                'ML',
                'MT',
                'MH',
                'MQ',
                'MR',
                'MU',
                'YT',
                'MX',
                'FM',
                'MD',
                'MC',
                'MN',
                'ME',
                'MS',
                'MA',
                'MZ',
                'MM',
                'NA',
                'NR',
                'NP',
                'NL',
                'AN',
                'NC',
                'NZ',
                'NI',
                'NE',
                'NG',
                'NU',
                'NF',
                'MP',
                'NO',
                'OM',
                'OT',
                'PK',
                'PW',
                'PS',
                'PA',
                'PG',
                'PY',
                'PE',
                'PH',
                'PN',
                'PL',
                'PT',
                'PR',
                'QA',
                'RE',
                'RO',
                'RU',
                'RW',
                'BL',
                'SH',
                'KN',
                'LC',
                'MF',
                'PM',
                'VC',
                'WS',
                'SM',
                'ST',
                'SA',
                'SN',
                'RS',
                'SC',
                'SL',
                'SG',
                'SK',
                'SI',
                'SB',
                'SO',
                'ZA',
                'GS',
                'ES',
                'LK',
                'SD',
                'SR',
                'SJ',
                'SZ',
                'SE',
                'CH',
                'SY',
                'TW',
                'TJ',
                'TZ',
                'TH',
                'TL',
                'TG',
                'TK',
                'TO',
                'TT',
                'TN',
                'TR',
                'TM',
                'TC',
                'TV',
                'UG',
                'UA',
                'AE',
                'GB',
                'US',
                'UM',
                'UY',
                'UZ',
                'VU',
                'VE',
                'VN',
                'VG',
                'VI',
                'WF',
                'EH',
                'YE',
                'ZM',
                'ZW'
            ],
            'DirectionFaces' => [
                'East',
                'North',
                'Northeast',
                'Northwest',
                'South',
                'Southeast',
                'Southwest',
                'West'
            ],
            'Electric' => [
                '220 Volts For Spa',
                '220 Volts in Garage',
                '220 Volts in Kitchen',
                '220 Volts in Laundry',
                '220 Volts in Workshop',
                'Photovoltaics Third-Party Owned',
                'Photovoltaics On Grid',
                'Photovoltaics Seller Owned',
                'Photovoltaics Stand-Alone',
                'Energy Storage Device',
                'Wind Turbine Seller Owned',
                'Wind Turbine Third-Party Owned',
                'Pre-Wired for Renewables',
                'Ready for Renewables\u00a0',
                'Net Meter',
                '100 Amp Service',
                '150 Amp Service',
                '200+ Amp Service',
                '440 Volts',
                'Circuit Breakers',
                'Fuses',
                '220 Volts',
                'Generator',
                'Underground'
            ],
            'LinearUnits' => [
                'Feet',
                'Meters'
            ],
            'FoundationDetails' => [
                'Block',
                'Brick\/Mortar',
                'Combination',
                'Concrete Perimeter',
                'None',
                'Permanent',
                'Pillar\/Post\/Pier',
                'Raised',
                'See Remarks',
                'Slab',
                'Stone'
            ],
            'Furnished' => [
                'Furnished',
                'Partially',
                'Unfurnished'
            ],
            'GreenEnergyEfficient' => [
                'Appliances',
                'Construction',
                'Doors',
                'Exposure\/Shade',
                'HVAC',
                'Incentives',
                'Insulation',
                'Lighting',
                'Roof',
                'Thermostat',
                'Water Heater',
                'Windows'
            ],
            'Languages' => [
                'Abkhazian',
                'Afar',
                'Afrikaans',
                'Albanian',
                'American Sign Language',
                'Amharic',
                'Arabic',
                'Aramaic',
                'Armenian',
                'Assamese',
                'Assyrian Neo-Aramaic',
                'Avestan',
                'Aymara',
                'Azerbaijani',
                'Bambara',
                'Bashkir',
                'Basque',
                'Bengali',
                'Bihari',
                'Bikol',
                'Bislama',
                'Bosnian',
                'Brazilian Portuguese',
                'Bulgarian',
                'Burmese',
                'Byelorussian',
                'Cambodian',
                'Cantonese',
                'Cape Verdean Creole',
                'Catalan',
                'Cebuano',
                'Chamorro',
                'Chechen',
                'Chinese',
                'Chuukese',
                'Chuvash',
                'Cornish',
                'Corsican',
                'Croatian',
                'Czech',
                'Danish',
                'Dari (Afghan Persian)',
                'Dioula',
                'Dutch',
                'Dzongkha',
                'English',
                'Esperanto',
                'Estonian',
                'Faroese',
                'Farsi',
                'Fiji',
                'Finnish',
                'Flemish',
                'French',
                'Frisian',
                'Galician',
                'Georgian',
                'German',
                'Greek',
                'Greenlandic',
                'Guarani',
                'Gujarati',
                'Haitian Creole',
                'Hausa',
                'Hebrew',
                'Herero',
                'Hiligaynon',
                'Hindi',
                'Hiri Motu',
                'Hmong',
                'Hungarian',
                'Iban',
                'Icelandic',
                'Igbo',
                'Ilocano',
                'Indonesian',
                'Interlingua',
                'Inuktitut',
                'Inupiak',
                'Irish (Gaelic)',
                'Italian',
                'Japanese',
                'Javanese',
                'Kannada',
                'Kashmiri',
                'Kazakh',
                'K\'iche',
                'Kichwa',
                'Kikuyu',
                'Kinyarwanda',
                'Kirghiz',
                'Kirundi',
                'Komi',
                'Korean',
                'Kpelle',
                'Kru',
                'Kurdish',
                'Lao',
                'Latin',
                'Latvian',
                'Lingala',
                'Lithuanian',
                'Luxemburgish',
                'Macedonian',
                'Malagasy',
                'Malay',
                'Malayalam',
                'Maltese',
                'Mandarin',
                'Maninka',
                'Manx Gaelic',
                'Maori',
                'Marathi',
                'Marshallese',
                'Moldovan',
                'Mongolian',
                'Nauru',
                'Navajo',
                'Ndebele',
                'Ndonga',
                'Nepali',
                'Norwegian',
                'Norwegian (Nynorsk)',
                'Nyanja',
                'Occitan',
                'Oriya',
                'Oromo',
                'Ossetian',
                'Pali',
                'Pangasinan',
                'Papiamento',
                'Pashto',
                'Polish',
                'Portuguese',
                'Punjabi',
                'Quechua',
                'Romanian',
                'Romany',
                'Russian',
                'Sami',
                'Samoan',
                'Sangho',
                'Sanskrit',
                'Sardinian',
                'Scots Gaelic',
                'Serbian',
                'Serbo-Croatian',
                'Sesotho',
                'Setswana',
                'Shan',
                'Shona',
                'Sindhi',
                'Sinhalese',
                'Siswati',
                'Slovak',
                'Slovenian',
                'Somali',
                'Southern Ndebele',
                'Spanish',
                'Sundanese',
                'Swahili',
                'Swedish',
                'Syriac',
                'Tagalog',
                'Tahitian',
                'Tajik',
                'Tamil',
                'Tatar',
                'Telugu',
                'Thai',
                'Tibetan',
                'Tigrinya',
                'Tongan',
                'Tsonga',
                'Turkish',
                'Turkmen',
                'Twi',
                'Uigur',
                'Ukrainian',
                'Urdu',
                'Uzbek',
                'Vietnamese',
                'Volapuk',
                'Welsh',
                'Wolof',
                'Xhosa',
                'Yiddish',
                'Yoruba',
                'Zhuang',
                'Zulu'
            ],
            'LockBoxType' => [
                'Call Listing Office',
                'Call Seller Direct',
                'Combo',
                'None',
                'See Remarks',
                'SentriLock',
                'Supra'
            ],
            'LotSizeSource' => [
                'Appraiser',
                'Assessor',
                'Builder',
                'Estimated',
                'Other',
                'Owner',
                'Plans',
                'Public Records',
                'See Remarks'
            ],
            'OwnerPays' => [
                'All Utilities',
                'Association Fees',
                'Cable TV',
                'Common Area Maintenance',
                'Electricity',
                'Exterior Maintenance',
                'Gas',
                'Grounds Care',
                'Hot Water',
                'HVAC Maintenance',
                'Insurance',
                'Janitorial Service',
                'Management',
                'None',
                'Other',
                'Other Tax',
                'Parking Fee',
                'Pest Control',
                'Pool Maintenance',
                'Repairs',
                'Roof Maintenance',
                'Security',
                'See Remarks',
                'Sewer',
                'Snow Removal',
                'Taxes',
                'Telephone',
                'Trash Collection',
                'Water'
            ],
            'PropertyCondition' => [
                'Fixer',
                'New Construction',
                'Under Construction',
                'Updated\/Remodeled'
            ],
            'RentIncludes' => [
                'All Utilities',
                'Cable TV',
                'Electricity',
                'Gardener',
                'Gas',
                'Internet',
                'Management',
                'None',
                'See Remarks',
                'Sewer',
                'Trash Collection',
                'Water'
            ],
            'Roof' => [
                'Aluminum',
                'Asbestos Shingle',
                'Asphalt',
                'Bahama',
                'Barrel',
                'Bituthene',
                'Built-Up',
                'Composition',
                'Concrete',
                'Copper',
                'Elastomeric',
                'Fiberglass',
                'Flat',
                'Flat Tile',
                'Foam',
                'Green Roof',
                'Mansard',
                'Membrane',
                'Metal',
                'Mixed',
                'None',
                'Other',
                'Rolled\/Hot Mop',
                'Rubber',
                'See Remarks',
                'Shake',
                'Shingle',
                'Slate',
                'Spanish Tile',
                'Stone',
                'Synthetic',
                'Tar\/Gravel',
                'Tile',
                'Wood'
            ],
            'Sewer' => [
                'Aerobic Septic',
                'Cesspool',
                'Engineered Septic',
                'Holding Tank',
                'Mound Septic',
                'None',
                'Other',
                'Perc Test On File',
                'Perc Test Required',
                'Private Sewer',
                'Public Sewer',
                'Septic Needed',
                'Septic Tank',
                'Shared Septic',
                'Unknown'
            ],
            'Skirt' => [
                'Aluminum',
                'Block',
                'Brick',
                'Combination',
                'Concrete',
                'Fiberglass',
                'Frame',
                'Glass',
                'Masonite',
                'Metal',
                'None',
                'Other',
                'Steel',
                'Stone',
                'Stucco',
                'Synthetic',
                'Unknown',
                'Vinyl',
                'Wood'
            ],
            'StreetDirection' => [
                'E',
                'N',
                'NE',
                'NW',
                'S',
                'SE',
                'SW',
                'W'
            ],
            'TenantPays' => [
                'All Utilities',
                'Association Fees',
                'Cable TV',
                'Common Area Maintenance',
                'Electricity',
                'Exterior Maintenance',
                'Gas',
                'Grounds Care',
                'Hot Water',
                'HVAC Maintenance',
                'Insurance',
                'Janitorial Service',
                'Management',
                'None',
                'Other',
                'Other Tax',
                'Parking Fee',
                'Pest Control',
                'Pool Maintenance',
                'Repairs',
                'Roof',
                'Security',
                'See Remarks',
                'Sewer',
                'Snow Removal',
                'Taxes',
                'Telephone',
                'Trash Collection',
                'Water'
            ],
            'Utilities' => [
                'Cable Available',
                'Cable Connected',
                'Cable Not Available',
                'Electricity Available',
                'Electricity Connected',
                'Electricity Not Available',
                'Natural Gas Available',
                'Natural Gas Connected',
                'Natural Gas Not Available',
                'None',
                'Other',
                'Phone Available',
                'Phone Connected',
                'Phone Not Available',
                'Propane',
                'See Remarks',
                'Sewer Available',
                'Sewer Connected',
                'Sewer Not Available',
                'Underground Utilities',
                'Water Available',
                'Water Connected',
                'Water Not Available'
            ],
            'WaterSource' => [
                'Cistern',
                'None',
                'Other',
                'Private',
                'Public',
                'See Remarks',
                'Shared Well',
                'Spring',
                'Well'
            ],
            'YearBuiltSource' => [
                'Appraiser',
                'Assessor',
                'Builder',
                'Estimated',
                'Other',
                'Owner',
                'Public Records',
                'See Remarks'
            ],
            'ImageOf' => [
                'Aerial View',
                'Atrium',
                'Attic',
                'Back of Structure',
                'Balcony',
                'Bar',
                'Barn',
                'Basement',
                'Bathroom',
                'Bedroom',
                'Bonus Room',
                'Breakfast Area',
                'Closet',
                'Community',
                'Courtyard',
                'Deck',
                'Den',
                'Dining Area',
                'Dining Room',
                'Dock',
                'Entry',
                'Exercise Room',
                'Family Room',
                'Fence',
                'Fireplace',
                'Floor Plan',
                'Front of Structure',
                'Game Room',
                'Garage',
                'Garden',
                'Golf Course',
                'Great Room',
                'Guest Quarters',
                'Gym',
                'Hobby Room',
                'Inlaw',
                'Kitchen',
                'Lake',
                'Laundry',
                'Library',
                'Living Room',
                'Loading Dock',
                'Lobby',
                'Loft',
                'Lot',
                'Master Bathroom',
                'Master Bedroom',
                'Media Room',
                'Mud Room',
                'Nursery',
                'Office',
                'Other',
                'Out Buildings',
                'Pantry',
                'Parking',
                'Patio',
                'Pier',
                'Plat Map',
                'Pond',
                'Pool',
                'Reception',
                'Recreation Room',
                'Sauna',
                'Showroom',
                'Side of Structure',
                'Sitting Room',
                'Spa',
                'Stable',
                'Storage',
                'Studio',
                'Study',
                'Sun Room',
                'View',
                'Waterfront',
                'Wine Cellar',
                'Workshop',
                'Yard'
            ],
            'PowerProductionType' => [
                'Photovoltaics',
                'Wind'
            ],
            'PowerProductionAnnualStatus' => [
                'Estimated',
                'Partially Estimated',
                'Actual'
            ],
            'GreenVerificationSource' => [
                'Administrator',
                'Assessor',
                'Builder',
                'Contractor or Installer',
                'Other',
                'Owner',
                'Program Sponsor',
                'Program Verifier',
                'Public Records',
                'See Remarks'
            ],
            'GreenEnergyGeneration' => [
                'Solar',
                'Wind'
            ],
            'GreenIndoorAirQuality' => [
                'Contaminant Control',
                'Moisture Control',
                'Ventilation',
                'Integrated Pest Management'
            ],
            'GreenSustainability' => [
                'Conserving Methods',
                'Regionally-Sourced Materials',
                'Recycled Materials',
                'Recyclable Materials',
                'Renewable Materials',
                'Salvaged Materials',
                'Onsite Recycling Center'
            ],
            'GreenWaterConservation' => [
                'Water-Smart Landscaping',
                'Green Infrastructure',
                'Gray Water System',
                'Water Recycling',
                'Efficient Hot Water Distribution',
                'Low-Flow Fixtures'
            ],
            'MlsStatus' => [
                'Active',
                'Pending',
                'Option Pending',
                'Kickout',
                'Contingent',
                'UCB (Under Contract-Backups)',
                'Closed',
                'Expired',
                'Pending',
                'Expired',
                'Withdrawn',
                'Cancelled',
                'Deleted',
                'Hold',
                'Coming Soon',
                'Backup',
            ],
            'StandardStatus' => [
                'Active',
                'Active Under Contract',
                'Pending',
                'Hold',
                'Withdrawn',
                'Closed',
                'Expired',
                'Canceled',
                'Delete',
                'Incomplete',
                'Coming Soon',
            ],
            'Exclusions' => [
                'Appliances',
                'Personal Property',
            ],
        ];
    }

    public function getDataValues($field_name)
    {
        $data = $this->getData();

        $return = [];

        if (isset($data[$field_name])) {
            $return = $data[$field_name];
        }

        return array_unique($return);
    }

    public function getDataKeys()
    {
        $data = $this->getData();

        return array_keys($data);
    }

    public function getSingleValues()
    {
        // these should be limited to one result
        return [
            "ListingService",
            "ListingAgreement",
            "LockboxLocation",
            "Exclusions",
            "Concessions",
            "Country",
            "PropertySubType",
            "AssociationFeeFrequency",
            "LotSizeSource",
            "LotSizeUnits",
            "OccupantType",
            "LeaseTerm",
            "Furnished",
            "BusinessType",
            "OwnershipType",
            "LeaseAmountFrequency",
            "HoursDaysofOperation",
            "Electric",
            "Gas",
            "Fencing",
            "OtherParking",
            "YearBuiltSource",
            "ArchitecturalStyle",
            "DirectionFaces",
            "Appliances",
        ];
    }
}