<?php


namespace FeedFaker\Helper;


class Enumerations
{
    public static function getEnums($field_name) {
        $enums = json_decode(self::$enums, true);

        if (array_key_exists($field_name, $enums)) {
            return $enums[$field_name];
        }

        return null;
    }

    public static $enums = '{
        "StandardStatus": [
        "Active",
        "Active Under Contract",
        "Pending",
        "Withdrawn",
        "Closed",
        "Expired",
        "Canceled",
        "Delete",
        "Incomplete",
        "Hold",
        "Coming Soon"
        ],
        "PropertySubType": [
        "Apartment",
        "Boat Slip",
        "Single Family Residence",
        "Deeded Parking",
        "Cabin",
        "Condominium",
        "Duplex",
        "Farm",
        "Manufactured Home",
        "Mobile Home",
        "Own Your Own",
        "Quadruplex",
        "Stock Cooperative",
        "Townhouse",
        "Timeshare",
        "Triplex",
        "Manufactured On Land",
        "Ranch"
        ],
        "FeeFrequency": [
        "Daily",
        "Weekly",
        "Bi-Weekly",
        "Semi-Monthly",
        "Monthly",
        "Bi-Monthly",
        "Quarterly",
        "Semi-Annually",
        "Annually",
        "Seasonal",
        "One Time"
        ],
        "RoomType": [
        "Dining Room",
        "Living Room",
        "Family Room",
        "Basement",
        "Kitchen",
        "Master Bedroom",
        "Bedroom 2",
        "Bedroom 3",
        "Bedroom 4",
        "Bedroom 5",
        "Master Bathroom",
        "Bathroom 2",
        "Bathroom 3",
        "Bathroom 4",
        "Bathroom 5",
        "Den",
        "Office",
        "Great Room",
        "Utility Room",
        "Workshop",
        "Laundry",
        "Loft",
        "Bonus Room",
        "Game Room",
        "Media Room",
        "Library",
        "Exercise Room",
        "Gym",
        "Sauna",
        "Bedroom 1",
        "Bathroom 1"
        ],
        "Levels": [
        "One",
        "Two",
        "Three Or More",
        "Multi\/Split"
        ],
        "BusinessType": [
        "Accounting",
        "Administrative and Support",
        "Advertising",
        "Agriculture",
        "Animal Grooming",
        "Appliances",
        "Aquarium Supplies",
        "Arts and Entertainment",
        "Athletic",
        "Auto Dealer",
        "Auto Service",
        "Bakery",
        "Bar\/Tavern\/Lounge",
        "Barber\/Beauty",
        "Bed & Breakfast",
        "Butcher",
        "Car Wash",
        "Child Care",
        "Church",
        "Clothing",
        "Commercial",
        "Computer",
        "Construction\/Contractor",
        "Convenience Store",
        "Dental",
        "Distribution",
        "Doughnut",
        "Dry Cleaner",
        "Education\/School",
        "Farm",
        "Fast Food",
        "Financial",
        "Fitness",
        "Florist\/Nursery",
        "Food & Beverage",
        "Forest Reserve",
        "Franchise",
        "Gas Station",
        "Gift Shop",
        "Grocery",
        "Hardware",
        "Health Services",
        "Hospitality",
        "Hotel\/Motel",
        "Ice Cream\/Frozen Yogurt",
        "Industrial",
        "Laundromat",
        "Liquor Store",
        "Manufacturing",
        "Medical",
        "Mixed",
        "Mobile\/Trailer Park",
        "Nursing Home",
        "Other",
        "Parking",
        "Pet Store",
        "Printing",
        "Professional Service",
        "Professional\/Office",
        "Recreation",
        "Residential",
        "Restaurant",
        "Retail",
        "Sporting Goods",
        "Storage",
        "Transportation",
        "Video",
        "Warehouse",
        "Wholesale",
        "Auto Body",
        "Auto Glass",
        "Auto Parts",
        "Auto Rent\/Lease",
        "Auto Repair-Specialty",
        "Auto Stereo\/Alarm",
        "Auto Tires",
        "Auto Wrecking",
        "Books\/Cards\/Stationary",
        "Cabinets",
        "Candy\/Cookie",
        "Carpet\/Tile",
        "Convalescent",
        "Dance Studio",
        "Decorator",
        "Deli\/Catering",
        "Drugstore",
        "Electronics",
        "Employment",
        "Furniture",
        "Health Food",
        "Hobby",
        "Home Cleaner",
        "Jewelry",
        "Landscaping",
        "Locksmith",
        "Music",
        "Office Supply",
        "Paints",
        "Photographer",
        "Pizza",
        "Real Estate",
        "Rental",
        "Saddlery\/Harness",
        "Toys",
        "Travel",
        "Upholstery",
        "Utility",
        "Variety",
        "Wallpaper"
        ],
        "CompensationType": [
        "$",
        "%",
        "See Remarks"
        ],
        "LeaseTerm": [
        "12 Months",
        "24 Months",
        "6 Months",
        "Month To Month",
        "Negotiable",
        "Weekly",
        "None",
        "Other",
        "Renewal Option",
        "Short Term Lease"
        ],
        "ListingAgreement": [
        "Exclusive Right To Lease",
        "Exclusive Agency",
        "Exclusive Right With Exception",
        "Exclusive Right To Sell",
        "Net",
        "Open",
        "Probate"
        ],
        "ListingService": [
        "Full Service",
        "Limited Service",
        "Entry Only"
        ],
        "AreaUnits": [
        "Square Feet",
        "Square Meters"
        ],
        "LotSizeUnits": [
        "Acres",
        "Square Feet",
        "Square Meters"
        ],
        "PropertyType": [
        "Residential",
        "Residential Lease",
        "Residential Income",
        "Manufactured In Park",
        "Land",
        "Commercial Sale",
        "Commercial Lease",
        "Business Opportunity",
        "Farm"
        ],
        "StateOrProvince": [
        "AK",
        "AL",
        "AR",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "GA",
        "HI",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "ME",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NC",
        "NE",
        "NH",
        "NJ",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "TN",
        "TX",
        "UT",
        "VA",
        "VI",
        "VT",
        "WA",
        "WI",
        "WY",
        "AB",
        "BC",
        "MB",
        "NB",
        "NF",
        "NS",
        "NT",
        "NU",
        "ON",
        "PE",
        "QC",
        "SK",
        "YT"
        ],
        "MemberStatus": [
        "Active",
        "Inactive"
        ],
        "OfficeStatus": [
        "Active",
        "Inactive"
        ],
        "ResourceName": [
        "Property",
        "Member",
        "Office",
        "Contacts"
        ],
        "OpenHouseType": [
        "Public",
        "Broker",
        "Office"
        ],
        "OpenHouseStatus": [
        "Active",
        "Canceled",
        "Ended"
        ],
        "AssociationFeeFrequency": [
        "Monthly",
        "Quarterly",
        "Yearly"
        ],
        "AssociationFeeIncludes": [
        "Cable TV",
        "Earthquake Insurance",
        "Electricity",
        "Gas",
        "Insurance",
        "Maintenance Exterior",
        "Maintenance Grounds",
        "Pest Control",
        "Security",
        "Sewer",
        "Snow Removal",
        "Trash",
        "Utilities",
        "Water"
        ],
        "Attended": [
        "Agent",
        "Seller",
        "Unattended"
        ],
        "BuyerFinancing": [
        "Assumed",
        "Cash",
        "Contract",
        "Conventional",
        "FHA",
        "FHA 203(b)",
        "FHA 203(k)",
        "Other",
        "Private",
        "Seller Financing",
        "Trust Deed",
        "USDA",
        "VA"
        ],
        "ClassName": [
        "Business Opportunity",
        "Commercial Lease",
        "Commercial Sale",
        "Contacts",
        "Cross Property",
        "Farm",
        "History Transactional",
        "Land",
        "Manufactured In Park",
        "Media",
        "Member",
        "Office",
        "Open House",
        "Residential",
        "Residential Income",
        "Residential Lease",
        "Saved Search"
        ],
        "CommonWalls": [
        "1 Common Wall",
        "2+ Common Walls",
        "End Unit",
        "No Common Walls",
        "No One Above",
        "No One Below"
        ],
        "CurrentFinancing": [
        "Assumable",
        "Contract",
        "Conventional",
        "FHA",
        "FHA 203(b)",
        "FHA 203(k)",
        "None",
        "Other",
        "Private",
        "Trust Deed",
        "USDA",
        "VA",
        "Leased Renewables",
        "Power Purchase Agreement",
        "Property-Assessed Clean Energy "
        ],
        "ExistingLeaseType": [
        "Absolute Net",
        "CPI Adjustment",
        "Escalation Clause",
        "Gross",
        "Ground Lease",
        "Net",
        "NN",
        "NNN",
        "Oral"
        ],
        "FinancialDataSource": [
        "Accountant",
        "Owner",
        "Property Manager"
        ],
        "IncomeIncludes": [
        "Laundry",
        "Parking",
        "Recreation",
        "Rent Only",
        "RV Storage",
        "Storage"
        ],
        "LandLeaseAmountFrequency": [
        "Month",
        "Week",
        "Year"
        ],
        "LeaseAmountFrequency": [
        "Month",
        "Week",
        "Year"
        ],
        "LeaseRenewalCompensation": [
        "Call Listing Agent",
        "Call Listing Office",
        "Commission Paid On Tenant Purchase",
        "No Renewal Commission",
        "Renewal Commission Paid"
        ],
        "ListingTerms": [
        "1031 Exchange",
        "All Inclusive Trust Deed",
        "Assumable",
        "Cash",
        "Contract",
        "Conventional",
        "Existing Bonds",
        "FHA",
        "Land Use Fee",
        "Lease Back",
        "Lease Option",
        "Lease Purchase",
        "Lien Release",
        "Owner May Carry",
        "Owner Pay Points",
        "Owner Will Carry",
        "Private Financing Available",
        "Relocation Property",
        "Seller Equity Share",
        "Special Funding",
        "Submit",
        "Trade",
        "Trust Conveyance",
        "Trust Deed",
        "USDA Loan",
        "VA Loan"
        ],
        "MediaCategory": [
        "Photo",
        "Video",
        "Branded Virtual Tour",
        "Unbranded Virtual Tour",
        "Document",
        "Floor Plan",
        "Office Logo",
        "Office Photo",
        "Agent Photo"
        ],
        "MediaType": [
        "gif",
        "jpeg",
        "png",
        "tiff",
        "mpeg",
        "mp4",
        "quicktime",
        "wmv",
        "pdf",
        "rtf",
        "txt",
        "doc",
        "docx",
        "xls",
        "xlsx"
        ],
        "MemberType": [
        "Association Staff",
        "Designated REALTOR Appraiser",
        "Designated REALTOR Participant",
        "MLS Only Appraiser",
        "MLS Only Broker",
        "MLS Only Salesperson",
        "MLS Staff",
        "Non Member\/Vendor",
        "Office Manager",
        "REALTOR Appraiser",
        "REALTOR Salesperson",
        "Unlicensed Assistant"
        ],
        "OccupantType": [
        "Owner",
        "Tenant",
        "Vacant"
        ],
        "TeamStatus": [
        "Active",
        "Inactive"
        ],
        "OfficeType": [
        "Association",
        "MLS",
        "MLS Only Branch",
        "MLS Only Firm",
        "MLS Only Office",
        "Non Member\/Vendor",
        "Realtor Branch Office",
        "Realtor Firm",
        "Realtor Office"
        ],
        "OperatingExpenseIncludes": [
        "Accounting",
        "Advertising",
        "Association",
        "Cable TV",
        "Capital Improvements",
        "Depreciation",
        "Equipment Rental",
        "Fuel",
        "Furniture Replacement",
        "Gardener",
        "Insurance",
        "Legal",
        "Licenses",
        "Maintenance",
        "Maintenance Grounds",
        "Maintenance Structure",
        "Manager",
        "Mortgage\/Loans",
        "New Tax",
        "Other",
        "Parking",
        "Pest Control",
        "Pool\/Spa",
        "Professional Management",
        "Security",
        "Snow Removal",
        "Staff",
        "Supplies",
        "Trash",
        "Utilities",
        "Vacancy Allowance",
        "Water\/Sewer",
        "Workmans Compensation"
        ],
        "OwnershipType": [
        "Corporation",
        "LLC",
        "Partnership",
        "Sole Proprietor"
        ],
        "Possession": [
        "Close Of Escrow",
        "Close Plus 1 Day",
        "Close Plus 2 Days",
        "Close Plus 3 Days",
        "Close Plus 3 to 5 Days",
        "Close Plus 30 Days",
        "Negotiable",
        "Rental Agreement",
        "See Remarks",
        "Seller Rent Back",
        "Subject To Tenant Rights"
        ],
        "ShowingContactType": [
        "Agent",
        "Occupant",
        "Owner",
        "Property Manager"
        ],
        "SpecialLicenses": [
        "Beer\/Wine",
        "Class H",
        "Entertainment",
        "Franchise",
        "Gambling",
        "Liquor",
        "Liquor 5 Years Or Less",
        "Liquor 5 Years Or More",
        "Liquor-Off Sale",
        "Liquor-On Sale",
        "None",
        "Other",
        "Professional"
        ],
        "SpecialListingConditions": [
        "Auction",
        "HUD Owned",
        "In Foreclosure",
        "Notice Of Default",
        "Probate Listing",
        "Real Estate Owned",
        "Short Sale",
        "Standard",
        "Third Party Approval",
        "Bankruptcy Property"
        ],
        "PetsAllowed": [
        "Yes",
        "No",
        "Call",
        "Cats OK",
        "Dogs OK",
        "Number Limit",
        "Size Limit",
        "Breed Restrictions"
        ],
        "HoursDaysofOperation": [
        "Open 24 Hours",
        "Open 8 Hours\/Day",
        "Open -8 Hours\/Day",
        "Open 8+ Hours\/Day",
        "Open 7 Days",
        "Open Monday-Friday",
        "Open Sunday",
        "Open Saturday",
        "Evenings Only"
        ],
        "GreenBuildingVerificationType": [
        "WaterSense",
        "ENERGY STAR Certified Homes",
        "Home Performance with ENERGY STAR",
        "Indoor airPLUS",
        "LEED For Homes",
        "NGBS New Construction",
        "NGBS Whole-Home Remodel",
        "NGBS Small Projects Remodel",
        "PHIUS+",
        "Certified Passive House",
        "EnerPHit",
        "Zero Energy Ready Home",
        "Living Building Challenge",
        "Home Energy Score",
        "HERS Index Score",
        "Home Energy Upgrade Certificate of Energy Efficiency Improvements",
        "Home Energy Upgrade Certificate of Energy Efficiency Performance"
        ],
        "ContactType": [
        "Lead"
        ],
        "AreaSource": [
        "Appraiser",
        "Assessor",
        "Builder",
        "Estimated",
        "Other",
        "Owner",
        "Plans",
        "Public Records",
        "See Remarks"
        ],
        "BodyType": [
        "Double Wide",
        "Expando",
        "Quad Wide",
        "See Remarks",
        "Single Wide",
        "Triple Wide"
        ],
        "ChangeType": [
        "Active",
        "Active Under Contract",
        "Back On Market",
        "Canceled",
        "Closed",
        "Deleted",
        "Expired",
        "Hold",
        "New Listing",
        "Pending",
        "Price Change",
        "Withdrawn"
        ],
        "Concessions": [
        "Call Listing Agent",
        "No",
        "Yes"
        ],
        "ConstructionMaterials": [
        "Adobe",
        "Aluminum Siding",
        "Asbestos",
        "Asphalt",
        "Block",
        "Blown-In Insulation",
        "Board & Batten Siding",
        "Brick",
        "Brick Veneer",
        "Cedar",
        "Cement Siding",
        "Clapboard",
        "Concrete",
        "Ducts Professionally Air-Sealed",
        "Fiber Cement",
        "Fiberglass Siding",
        "Frame",
        "Glass",
        "HardiPlank Type",
        "ICFs (Insulated Concrete Forms)",
        "Lap Siding",
        "Log",
        "Log Siding",
        "Masonite",
        "Metal Siding",
        "Natural Building",
        "Other",
        "Plaster",
        "Radiant Barrier",
        "Rammed Earth",
        "Redwood Siding",
        "See Remarks",
        "Shake Siding",
        "Shingle Siding",
        "Slump Block",
        "Spray Foam Insulation",
        "Steel Siding",
        "Stone",
        "Stone Veneer",
        "Straw",
        "Stucco",
        "Synthetic Stucco",
        "Unknown",
        "Vertical Siding",
        "Vinyl Siding",
        "Wood Siding",
        "Attic\/Crawl Hatchway(s) Insulated",
        "Batts Insulation",
        "Exterior Duct-Work is Insulated",
        "Foam Insulation",
        "ICAT Recessed Lighting",
        "Low VOC Insulation",
        "Recycled\/Bio-Based Insulation"
        ],
        "Country": [
        "AF",
        "AL",
        "DZ",
        "AS",
        "AD",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AM",
        "AW",
        "AU",
        "AT",
        "AZ",
        "BS",
        "BH",
        "BD",
        "BB",
        "BY",
        "BE",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BA",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BG",
        "BF",
        "BI",
        "KH",
        "CM",
        "CA",
        "CV",
        "KY",
        "CF",
        "TD",
        "CL",
        "CN",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "HR",
        "CU",
        "CY",
        "CZ",
        "DK",
        "DJ",
        "DM",
        "DO",
        "EC",
        "EG",
        "SV",
        "GQ",
        "ER",
        "EE",
        "ET",
        "FK",
        "FO",
        "FJ",
        "FI",
        "FR",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GE",
        "DE",
        "GH",
        "GI",
        "GR",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "VA",
        "HN",
        "HK",
        "HU",
        "IS",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IE",
        "IM",
        "IL",
        "IT",
        "JM",
        "JP",
        "JE",
        "JO",
        "KZ",
        "KE",
        "KI",
        "KP",
        "KR",
        "KW",
        "KG",
        "LA",
        "LV",
        "LB",
        "LS",
        "LR",
        "LY",
        "LI",
        "LT",
        "LU",
        "MO",
        "MK",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MT",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MD",
        "MC",
        "MN",
        "ME",
        "MS",
        "MA",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NL",
        "AN",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "MP",
        "NO",
        "OM",
        "OT",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PL",
        "PT",
        "PR",
        "QA",
        "RE",
        "RO",
        "RU",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "SM",
        "ST",
        "SA",
        "SN",
        "RS",
        "SC",
        "SL",
        "SG",
        "SK",
        "SI",
        "SB",
        "SO",
        "ZA",
        "GS",
        "ES",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SZ",
        "SE",
        "CH",
        "SY",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TN",
        "TR",
        "TM",
        "TC",
        "TV",
        "UG",
        "UA",
        "AE",
        "GB",
        "US",
        "UM",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW"
        ],
        "DirectionFaces": [
        "East",
        "North",
        "Northeast",
        "Northwest",
        "South",
        "Southeast",
        "Southwest",
        "West"
        ],
        "Electric": [
        "220 Volts For Spa",
        "220 Volts in Garage",
        "220 Volts in Kitchen",
        "220 Volts in Laundry",
        "220 Volts in Workshop",
        "Photovoltaics Third-Party Owned",
        "Photovoltaics On Grid",
        "Photovoltaics Seller Owned",
        "Photovoltaics Stand-Alone",
        "100 Amp Service",
        "150 Amp Service",
        "200+ Amp Service",
        "440 Volts",
        "Circuit Breakers",
        "Fuses",
        "220 Volts",
        "Generator",
        "Underground",
        "Energy Storage Device",
        "Wind Turbine Seller Owned",
        "Wind Turbine Third-Party Owned",
        "Pre-Wired for Renewables",
        "Net Meter"
        ],
        "LinearUnits": [
        "Feet",
        "Meters"
        ],
        "FoundationDetails": [
        "Block",
        "Brick\/Mortar",
        "Combination",
        "Concrete Perimeter",
        "None",
        "Permanent",
        "Pillar\/Post\/Pier",
        "Raised",
        "See Remarks",
        "Slab",
        "Stone"
        ],
        "Furnished": [
        "Furnished",
        "Partially",
        "Unfurnished"
        ],
        "GreenEnergyEfficient": [
        "Appliances",
        "Construction",
        "Doors",
        "Exposure\/Shade",
        "HVAC",
        "Incentives",
        "Insulation",
        "Lighting",
        "Roof",
        "Thermostat",
        "Water Heater",
        "Windows"
        ],
        "Languages": [
        "Abkhazian",
        "Afar",
        "Afrikaans",
        "Albanian",
        "American Sign Language",
        "Amharic",
        "Arabic",
        "Aramaic",
        "Armenian",
        "Assamese",
        "Assyrian Neo-Aramaic",
        "Avestan",
        "Aymara",
        "Azerbaijani",
        "Bambara",
        "Bashkir",
        "Basque",
        "Bengali",
        "Bihari",
        "Bikol",
        "Bislama",
        "Bosnian",
        "Brazilian Portuguese",
        "Bulgarian",
        "Burmese",
        "Byelorussian",
        "Cambodian",
        "Cantonese",
        "Cape Verdean Creole",
        "Catalan",
        "Cebuano",
        "Chamorro",
        "Chechen",
        "Chinese",
        "Chuukese",
        "Chuvash",
        "Cornish",
        "Corsican",
        "Croatian",
        "Czech",
        "Danish",
        "Dari (Afghan Persian)",
        "Dioula",
        "Dutch",
        "Dzongkha",
        "English",
        "Esperanto",
        "Estonian",
        "Faroese",
        "Farsi",
        "Fiji",
        "Finnish",
        "Flemish",
        "French",
        "Frisian",
        "Galician",
        "Georgian",
        "German",
        "Greek",
        "Greenlandic",
        "Guarani",
        "Gujarati",
        "Haitian Creole",
        "Hausa",
        "Hebrew",
        "Herero",
        "Hiligaynon",
        "Hindi",
        "Hiri Motu",
        "Hmong",
        "Hungarian",
        "Iban",
        "Icelandic",
        "Igbo",
        "Ilocano",
        "Indonesian",
        "Interlingua",
        "Inuktitut",
        "Inupiak",
        "Irish (Gaelic)",
        "Italian",
        "Japanese",
        "Javanese",
        "Kannada",
        "Kashmiri",
        "Kazakh",
        "K\'iche",
        "Kichwa",
        "Kikuyu",
        "Kinyarwanda",
        "Kirghiz",
        "Kirundi",
        "Komi",
        "Korean",
        "Kpelle",
        "Kru",
        "Kurdish",
        "Lao",
        "Latin",
        "Latvian",
        "Lingala",
        "Lithuanian",
        "Luxemburgish",
        "Macedonian",
        "Malagasy",
        "Malay",
        "Malayalam",
        "Maltese",
        "Mandarin",
        "Maninka",
        "Manx Gaelic",
        "Maori",
        "Marathi",
        "Marshallese",
        "Moldovan",
        "Mongolian",
        "Nauru",
        "Navajo",
        "Ndebele",
        "Ndonga",
        "Nepali",
        "Norwegian",
        "Norwegian (Nynorsk)",
        "Nyanja",
        "Occitan",
        "Oriya",
        "Oromo",
        "Ossetian",
        "Pali",
        "Pangasinan",
        "Papiamento",
        "Pashto",
        "Polish",
        "Portuguese",
        "Punjabi",
        "Quechua",
        "Romanian",
        "Romany",
        "Russian",
        "Sami",
        "Samoan",
        "Sangho",
        "Sanskrit",
        "Sardinian",
        "Scots Gaelic",
        "Serbian",
        "Serbo-Croatian",
        "Sesotho",
        "Setswana",
        "Shan",
        "Shona",
        "Sindhi",
        "Sinhalese",
        "Siswati",
        "Slovak",
        "Slovenian",
        "Somali",
        "Southern Ndebele",
        "Spanish",
        "Sundanese",
        "Swahili",
        "Swedish",
        "Syriac",
        "Tagalog",
        "Tahitian",
        "Tajik",
        "Tamil",
        "Tatar",
        "Telugu",
        "Thai",
        "Tibetan",
        "Tigrinya",
        "Tongan",
        "Tsonga",
        "Turkish",
        "Turkmen",
        "Twi",
        "Uigur",
        "Ukrainian",
        "Urdu",
        "Uzbek",
        "Vietnamese",
        "Volapuk",
        "Welsh",
        "Wolof",
        "Xhosa",
        "Yiddish",
        "Yoruba",
        "Zhuang",
        "Zulu"
        ],
        "LockBoxType": [
        "Call Listing Office",
        "Call Seller Direct",
        "Combo",
        "None",
        "See Remarks",
        "SentriLock",
        "Supra"
        ],
        "LotSizeSource": [
        "Appraiser",
        "Assessor",
        "Builder",
        "Estimated",
        "Other",
        "Owner",
        "Plans",
        "Public Records",
        "See Remarks"
        ],
        "OwnerPays": [
        "All Utilities",
        "Association Fees",
        "Cable TV",
        "Common Area Maintenance",
        "Electricity",
        "Exterior Maintenance",
        "Gas",
        "Grounds Care",
        "Hot Water",
        "HVAC Maintenance",
        "Insurance",
        "Janitorial Service",
        "Management",
        "None",
        "Other",
        "Other Tax",
        "Parking Fee",
        "Pest Control",
        "Pool Maintenance",
        "Repairs",
        "Roof Maintenance",
        "Security",
        "See Remarks",
        "Sewer",
        "Snow Removal",
        "Taxes",
        "Telephone",
        "Trash Collection",
        "Water"
        ],
        "PropertyCondition": [
        "Fixer",
        "New Construction",
        "Under Construction",
        "Updated\/Remodeled"
        ],
        "RentIncludes": [
        "All Utilities",
        "Cable TV",
        "Electricity",
        "Gardener",
        "Gas",
        "Internet",
        "Management",
        "None",
        "See Remarks",
        "Sewer",
        "Trash Collection",
        "Water"
        ],
        "Roof": [
        "Aluminum",
        "Asbestos Shingle",
        "Asphalt",
        "Bahama",
        "Barrel",
        "Bituthene",
        "Built-Up",
        "Composition",
        "Concrete",
        "Copper",
        "Elastomeric",
        "Fiberglass",
        "Flat",
        "Flat Tile",
        "Foam",
        "Green Roof",
        "Mansard",
        "Membrane",
        "Metal",
        "Mixed",
        "None",
        "Other",
        "Rolled\/Hot Mop",
        "Rubber",
        "See Remarks",
        "Shake",
        "Shingle",
        "Slate",
        "Spanish Tile",
        "Stone",
        "Synthetic",
        "Tar\/Gravel",
        "Tile",
        "Wood"
        ],
        "Sewer": [
        "Aerobic Septic",
        "Cesspool",
        "Engineered Septic",
        "Holding Tank",
        "Mound Septic",
        "None",
        "Other",
        "Perc Test On File",
        "Perc Test Required",
        "Private Sewer",
        "Public Sewer",
        "Septic Needed",
        "Septic Tank",
        "Shared Septic",
        "Unknown"
        ],
        "Skirt": [
        "Aluminum",
        "Block",
        "Brick",
        "Combination",
        "Concrete",
        "Fiberglass",
        "Frame",
        "Glass",
        "Masonite",
        "Metal",
        "None",
        "Other",
        "Steel",
        "Stone",
        "Stucco",
        "Synthetic",
        "Unknown",
        "Vinyl",
        "Wood"
        ],
        "StreetDirection": [
        "E",
        "N",
        "NE",
        "NW",
        "S",
        "SE",
        "SW",
        "W"
        ],
        "TenantPays": [
        "All Utilities",
        "Association Fees",
        "Cable TV",
        "Common Area Maintenance",
        "Electricity",
        "Exterior Maintenance",
        "Gas",
        "Grounds Care",
        "Hot Water",
        "HVAC Maintenance",
        "Insurance",
        "Janitorial Service",
        "Management",
        "None",
        "Other",
        "Other Tax",
        "Parking Fee",
        "Pest Control",
        "Pool Maintenance",
        "Repairs",
        "Roof",
        "Security",
        "See Remarks",
        "Sewer",
        "Snow Removal",
        "Taxes",
        "Telephone",
        "Trash Collection",
        "Water"
        ],
        "Utilities": [
        "Cable Available",
        "Cable Connected",
        "Cable Not Available",
        "Electricity Available",
        "Electricity Connected",
        "Electricity Not Available",
        "Natural Gas Available",
        "Natural Gas Connected",
        "Natural Gas Not Available",
        "None",
        "Other",
        "Phone Available",
        "Phone Connected",
        "Phone Not Available",
        "Propane",
        "See Remarks",
        "Sewer Available",
        "Sewer Connected",
        "Sewer Not Available",
        "Underground Utilities",
        "Water Available",
        "Water Connected",
        "Water Not Available"
        ],
        "WaterSource": [
        "Cistern",
        "None",
        "Other",
        "Private",
        "Public",
        "See Remarks",
        "Shared Well",
        "Spring",
        "Well"
        ],
        "YearBuiltSource": [
        "Appraiser",
        "Assessor",
        "Builder",
        "Estimated",
        "Other",
        "Owner",
        "Public Records",
        "See Remarks"
        ],
        "ImageOf": [
        "Aerial View",
        "Atrium",
        "Attic",
        "Back of Structure",
        "Balcony",
        "Bar",
        "Barn",
        "Basement",
        "Bathroom",
        "Bedroom",
        "Bonus Room",
        "Breakfast Area",
        "Closet",
        "Community",
        "Courtyard",
        "Deck",
        "Den",
        "Dining Area",
        "Dining Room",
        "Dock",
        "Entry",
        "Exercise Room",
        "Family Room",
        "Fence",
        "Fireplace",
        "Floor Plan",
        "Front of Structure",
        "Game Room",
        "Garage",
        "Garden",
        "Golf Course",
        "Great Room",
        "Guest Quarters",
        "Gym",
        "Hobby Room",
        "Inlaw",
        "Kitchen",
        "Lake",
        "Laundry",
        "Library",
        "Living Room",
        "Loading Dock",
        "Lobby",
        "Loft",
        "Lot",
        "Master Bathroom",
        "Master Bedroom",
        "Media Room",
        "Mud Room",
        "Nursery",
        "Office",
        "Other",
        "Out Buildings",
        "Pantry",
        "Parking",
        "Patio",
        "Plat Map",
        "Pond",
        "Pool",
        "Recreation Room",
        "Sauna",
        "Showroom",
        "Side of Structure",
        "Sitting Room",
        "Spa",
        "Stable",
        "Storage",
        "Studio",
        "Study",
        "Sun Room",
        "View",
        "Waterfront",
        "Wine Cellar",
        "Workshop",
        "Yard",
        "Reception",
        "Pier"
        ],
        "PowerProductionType": [
        "Wind"
        ],
        "PowerProductionAnnualStatus": [
        "Estimated",
        "Partially Estimated",
        "Actual"
        ],
        "GreenVerificationSource": [
        "Administrator",
        "Assessor",
        "Builder",
        "Contractor or Installer",
        "Other",
        "Owner",
        "Program Sponsor",
        "Program Verifier",
        "Public Records",
        "See Remarks"
        ],
        "GreenIndoorAirQuality": [
        "Contaminant Control",
        "Moisture Control",
        "Ventilation",
        "Integrated Pest Management"
        ],
        "GreenSustainability": [
        "Conserving Methods",
        "Regionally-Sourced Materials",
        "Recycled Materials",
        "Recyclable Materials",
        "Renewable Materials",
        "Salvaged Materials",
        "Onsite Recycling Center"
        ],
        "GreenWaterConservation": [
        "Water-Smart Landscaping",
        "Green Infrastructure",
        "Gray Water System",
        "Water Recycling",
        "Efficient Hot Water Distribution",
        "Low-Flow Fixtures"
        ]
        }';
}